Sandstorm:
  Newsletter:
    receiverSourceTypes:
      'TtreeReceiverSourceMerger':
        label: 'Receiver Group Merger'
        className: \Ttree\Newsletter\ReveiverSourceMerger\Domain\Model\ReceiverSourceMerger
